[package]
name = "barycenter"
version = "0.1.0"
authors = ["Joel Moore <47923231+JMoore96@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7"
rayon = "1"